title: Seyong's Technical Blog
email: seyong@seyongcho.com
description: >- # this means to ignore newlines until "baseurl:"
  Writing about anything technical.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  se468
google_analytics: UA-108070297-1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
